### ISSUE TITLE
Which neuromorphic hardware does SpKeras simulate ?

### ISSUE THREAD

**Issue by sauravtii** [Dengyu-Wu/spkeras#5]
Hello,

I have been recently using SpKeras, but I am still not sure which neuromorphic hardware does it simulate ?
For example,
I used it to create an ANN, convert it to SNN and then simulate the SNN using SpKeras. But which neuromorphic hardware does SpKeras use to simulate SNNs ?

Also, the code the network architecture that I tried simulating is [this](https://github.com/Dengyu-Wu/spkeras/issues/4)

**Comment by Dengyu-Wu** [comment]
Hi, 

So far, Spkeras does not target at any neuromorphic hardware, but it simply simulates the number of spike generated by the IF neuron that mimics the forward propagation in neuromorphics.

**Comment by sauravtii** [comment]
Okay, so you mean to say that the simulation of SNN is carried out on CPU/GPU, right ?

**Comment by Dengyu-Wu** [comment]
Yes

**Comment by sauravtii** [comment]
Okay, thanks!

**Comment by sauravtii** [comment]
Hi, sorry for the follow up but I had one more question.

Basically, most of the SNN simulators imitate some neuromorphic hardware, for ex. NengoLoihi imitates Intel Loihi, so it means that they are running the SNN on the copy of Loihi but the required computations are carried out on CPU/GPU, likewise does SpKeras imitate any neuromorphic hardware for the simulation of SNN provided that the computations are done on CPU/GPU ?

**Comment by Dengyu-Wu** [comment]
No, it does not. The one thing SpKeras can do is that you can quantise the weights during conversion, for example, apply the signed_bit attribute with 4,5,7 or 8 bit signed quantisation. The accuracy will be closer to the hardware implementation, since neuromorphics only support limited precision of weight, for example, loihi supports 1-9 bit weights (https://en.wikichip.org/wiki/intel/loihi).
